ros2/rmw_implementation

- rmw_implementation/package.xml
Connects to ros2/rmw_connext#28
> rename rmw connext dynamic package

- rmw_implementation/CMakeLists.txt
Connect to ament/ament_cmake#68
> use CTest BUILD_TESTING

- rmw_implementation/CMakeLists.txt
- rmw_implementation/rmw_implementation-extras.cmake.in
Connect to ament/ament_cmake#72
> require CMake 3.5

- rmw_implementation/src/functions.cpp
> expose list of nodes

- rmw_implementation/src/functions.cpp
> pass new namespace_ argument through rmw_create_node

- rmw_implementation/CMakeLists.txt
- rmw_implementation/package.xml
- rmw_implementation/src/functions.cpp
> use string_array_t from c_utilities package

- rmw_implementation/CMakeLists.txt
- rmw_implementation/package.xml
- rmw_implementation/src/functions.cpp
Connects to ros2/c_utilities#17
> rename {c_}utilities to rcutils

- rmw_implementation/src/functions.cpp
> Add security_options to rmw_create_node argument list

- rmw_implementation/src/functions.cpp
Connect to ament/uncrustify#18.
> update style to match latest uncrustify

- rmw_implementation/src/functions.cpp
> waitset -> wait_set

- rmw_implementation/package.xml
As discussed in todays meeting.
> rename dependency group

- rmw_implementation/src/functions.cpp
Fixes #33.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3971)](http://ci.ros2.org/job/ci_linux/3971/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1084)](http://ci.ros2.org/job/ci_linux-aarch64/1084/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3308)](http://ci.ros2.org/job/ci_osx/3308/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=4072)](http://ci.ros2.org/job/ci_windows/4072/)
> improve error messages

- rmw_implementation/src/functions.cpp
> *_raw function

- rmw_implementation/package.xml
Fast forward this commit to master if approved.
> Prepare 0.5.0

- rmw_implementation/src/functions.cpp
> add rmw_get_encoding_identifier

- rmw_implementation/src/functions.cpp
> Include node namespaces in get_node_names

- rmw_implementation/src/functions.cpp
> Methods to retrieve matched count on pub/sub.

- rmw_implementation/src/functions.cpp
> add new functions

- rmw_implementation/src/functions.cpp
* rmw_get_subscriber_names_and_types_by_node
* rmw_get_publisher_names_and_types_by_node
* rmw_get_service_names_and_types_by_node
Connects to ros2/rcl#333
> Add node graph functions

- rmw_implementation/src/functions.cpp
> pass context to wait set and fini context

- rmw_implementation/src/functions.cpp
> add missing preload of rmw_set_log_severity

- rmw_implementation/src/functions.cpp
Add new function https://github.com/ros2/rmw/pull/169
Connects to ros2/rmw#169
> Add function to get publisher actual qos settings

- rmw_implementation/src/functions.cpp
Connects to https://github.com/ros2/rmw/pull/179
> Add function for getting clients by node

- rmw_implementation/src/functions.cpp
> update signature for added pub/sub options

- rmw_implementation/package.xml
Context: https://github.com/ros2/ros2/issues/786
Related: ros2/ci#340
> Add support for Cyclone DDS

- rmw_implementation/package.xml
Fixes regression from https://github.com/ros2/rmw_implementation/pull/82#discussion_r406554230
> fix dependency on rmw_implementation_cmake

- rmw_implementation/src/functions.cpp
Signed-off-by: Mikael Arguedas <mikael.arguedas@gmail.com>
> security-context -> enclave

- rmw_implementation/src/functions.cpp
This PR builds on top of this other PR https://github.com/ros2/rcpputils/pull/55
Removed duplicate get_env_var
> Using get_env_var from rcpputils

- rmw_implementation/CMakeLists.txt
> export targets in a addition to include directories / libraries

- rmw_implementation/src/functions.cpp
Connects to ros2/rmw#212
Signed-off-by: Michael Carroll <michael@openrobotics.org>
> Add take_sequence to RMW API

- QUALITY_DECLARATION.md
- README.md
This is a quality declaration for rmw_implementation as described in the proposed REP-2004 (see ros-infrastructure/rep#218).
This declaration is aspirational, in that it states things which aren't currently true, but we plan to do soon so we can get it up to the highest level.
Checklist in #89 can be checked first to sort out missing parts of the declaration.
> Added quality declaration

- README.md
Precisely what the title says.
> Update README.md with feature documentation.

- rmw_implementation/src/functions.cpp
See https://github.com/ros2/rmw/pull/227.
> Remove MANUAL_BY_NODE liveliness API

- QUALITY_DECLARATION.md
Signed-off-by: Stephen Brawner <brawner@gmail.com>
> Update QDs for 1.0

- QUALITY_DECLARATION.md
- README.md
Precisely what the title says.
> Update Quality Declaration to QL3.

- rmw_implementation/src/functions.cpp
See https://github.com/ros2/rcl/pull/708.
> Remove domain_id and localhost_only from node API

- test_rmw_implementation/CMakeLists.txt
- test_rmw_implementation/package.xml
- test_rmw_implementation/test/test_publisher.cpp
Depends on https://github.com/ros2/rmw/pull/252.
> Add publisher API test coverage

- test_rmw_implementation/CMakeLists.txt
- test_rmw_implementation/test/test_subscription.cpp
Depends on https://github.com/ros2/rmw/pull/256. Built on top of #115.
> Add subscription API test coverage

- test_rmw_implementation/test/test_publisher.cpp
Related to https://github.com/ros2/rmw/pull/270
> Add tests non-implemented functions + loan bad arguments

- test_rmw_implementation/test/test_publisher.cpp
> Add tests publish bad arguments

- test_rmw_implementation/test/test_publisher.cpp
> Add tests publish serialized bad arguments

- test_rmw_implementation/test/test_subscription.cpp
> Add tests for non-implemented rmw_take_* functions

- test_rmw_implementation/CMakeLists.txt
- test_rmw_implementation/package.xml
- test_rmw_implementation/test/test_subscription.cpp
> Add tests take with info bad arguments

- test_rmw_implementation/test/test_subscription.cpp
Adds tests for checking returns on bad arguments for `rmw_take_sequence`
> Add tests take sequence + take sequence with bad arguments

- test_rmw_implementation/test/test_subscription.cpp
> Add tests take sequence serialized with bad arguments

- test_rmw_implementation/CMakeLists.txt
- test_rmw_implementation/test/test_subscription.cpp
> Add tests take serialized with info bad arguments 

- test_rmw_implementation/test/test_create_destroy_node.cpp
Tests added to up line-based coverage on rmw_implementations
> Add tests for localhost-only node creation

- rmw_implementation/QUALITY_DECLARATION.md
Almost the same as #147, but bumping to QL2 instead.
> Update Quality Declaration to QL2.

- rmw_implementation/QUALITY_DECLARATION.md
> Updated performance QD section

- rmw_implementation/package.xml
> Restored Dirk as author

- rmw_implementation/package.xml
> Eloquent updated maintainers

- rmw_implementation/package.xml
> Foxy updated maintainers

- test_rmw_implementation/CMakeLists.txt
- test_rmw_implementation/package.xml
- test_rmw_implementation/test/allocator_testing_utils.h
- test_rmw_implementation/test/config.hpp
- test_rmw_implementation/test/test_client.cpp
- test_rmw_implementation/test/test_create_destroy_node.cpp
- test_rmw_implementation/test/test_graph_api.cpp
- test_rmw_implementation/test/test_init_options.cpp
- test_rmw_implementation/test/test_init_shutdown.cpp
- test_rmw_implementation/test/test_publisher.cpp
- test_rmw_implementation/test/test_publisher_allocator.cpp
- test_rmw_implementation/test/test_serialize_deserialize.cpp
- test_rmw_implementation/test/test_service.cpp
- test_rmw_implementation/test/test_subscription.cpp
- test_rmw_implementation/test/test_subscription_allocator.cpp
- test_rmw_implementation/test/test_unique_identifiers.cpp
- test_rmw_implementation/test/test_wait_set.cpp
- test_rmw_implementation/test/testing_macros.hpp
This PR depends on these three PR that improve the quality of the rmw implementation of the following vendors:
- https://github.com/ros2/rmw_fastrtps/pull/462
- https://github.com/ros2/rmw_cyclonedds/pull/255
- https://github.com/ros2/rmw_connext/pull/469
This PR
- Split the package in two: rmw_implementation and test_rmw_implementation
- Add and improve tests
> [Backport Foxy] Increased rmw implementation code coverage

- rmw_implementation/CMakeLists.txt
- rmw_implementation/package.xml
- rmw_implementation/src/functions.cpp
- rmw_implementation/src/functions.hpp
- rmw_implementation/src/visibility_control.h
- rmw_implementation/test/benchmark/benchmark_symbols.cpp
- rmw_implementation/test/test_functions.cpp
Added `rmw_implementation` benchmark and tests
> [Backport Foxy] Added implementation benchmark and test

- rmw_implementation/QUALITY_DECLARATION.md
- rmw_implementation/README.md
Signed-off-by: Stephen Brawner <brawner@gmail.com>
> Update QD to QL 1

- rmw_implementation/src/functions.cpp
- test_rmw_implementation/CMakeLists.txt
- test_rmw_implementation/test/test_qos_profile_check_compatible.cpp
Connected to https://github.com/ros2/rmw/pull/299
> Add function for checking QoS profile compatibility

- rmw_implementation/package.xml
- test_rmw_implementation/test/config.hpp
> Remove rmw_connext_cpp.

- rmw_implementation/QUALITY_DECLARATION.md
Updating obsolete links in the QUALITY_DECLARATION.md files, re: ros2/docs.ros2.org#52
> Updating Quality Declaration

- rmw_implementation/QUALITY_DECLARATION.md
Updating obsolete links in the QUALITY_DECLARATION.md files, re: ros2/docs.ros2.org#52
Signed-off-by: Simon Honigmann <shonigmann@blueorigin.com>
> updating quality declaration links (re: ros2/docs.ros2.org#52)

- rmw_implementation/src/functions.cpp
Connected to https://github.com/ros2/rmw/pull/318.
> Add rmw_feature_supported()

- rmw_implementation/src/functions.cpp
- test_rmw_implementation/test/test_unique_identifiers.cpp
See: https://github.com/ros2/rmw/pull/327
Signed-off-by: Brian Chen <brian.chen@openrobotics.org>
> Add rmw_get_gid_for_client & tests

- rmw_implementation/QUALITY_DECLARATION.md
* Update branch name in links (`/master/` -> `/rolling/`)
* Apply one-sentence-per-line rule in some places
> Update quality declaration document

- test_rmw_implementation/test/test_create_destroy_node.cpp
comes with https://github.com/ros2/rcl/pull/1169
> remove rmw_localhost_only_t.
