rmw_implementation/cmake/add_executable_for_each_rmw_implementation.cmake
rmw_implementation/rmw_implementation-extras.cmake

http://ci.ros2.org/job/ros2_batch_ci_linux/226/
http://ci.ros2.org/job/ros2_batch_ci_osx/147/
http://ci.ros2.org/job/ros2_batch_ci_windows/227/

add add_executable_for_each_rmw_implementations()

---

rmw_implementation/cmake/add_executable_for_each_rmw_implementation.cmake
rmw_implementation/cmake/get_default_rmw_implementation.cmake

Invoke `find_package()` in the root scope (rather then in a function scope) to prevent finding the same package repeatedly. E.g. http://ci.ros2.org/job/ros2_batch_ci_linux/320/consoleFull#console-section-74
http://ci.ros2.org/job/ros2_batch_ci_linux/331/consoleFull#console-section-73

find_package() in root scope

---

rmw_implementation/cmake/add_executable_for_each_rmw_implementation.cmake

This was introduced by https://github.com/ros2/rmw_implementation/pull/5.
The result was that no implementation specific binaries were created on my machine.

fix missed variable name in refactoring

---

rmw_implementation/package.xml

Otherwise `rmw_fastrtps_cpp` might not be built before `rclcpp`.

add dependency on rmw_fastrtps_cpp

---

rmw_implementation/CMakeLists.txt
rmw_implementation/package.xml
rmw_implementation/rmw_implementation-extras.cmake.in

This is work-in-progress.
It currently builds with a single RMW impl. on Linux and OS X.

refactor typesupport

---

rmw_implementation/package.xml
rmw_implementation/rmw_implementation-extras.cmake.in

raised from discussion in https://github.com/ros2/rmw_implementation/issues/10

Detect if conflicting default rmw implementations have been specified

---

rmw_implementation/CMakeLists.txt

Looks like this:
```
...
-- Found OpenSplice: ...
--
-- Found these rmw implementations:
--   'rmw_connext_cpp'
--   'rmw_connext_dynamic_cpp'
--   'rmw_opensplice_cpp'
--
-- Using default rmw implementation: 'rmw_opensplice_cpp'
--
-- Added test 'lint_cmake' to check CMake code style
...
```

add messages as cmake output that displays the discovered rmw impls and the default

---

rmw_implementation/CMakeLists.txt
rmw_implementation/package.xml
rmw_implementation/rmw_implementation-extras.cmake.in
rmw_implementation/src/functions.cpp

This patch makes `rmw_implementation` an actual rmw implementation. If only a single rmw impl. is available or Poco is unavailable it simply redirects to the default rmw implementation. Otherwise it acts a dynamic dispatch to any rmw implementation selected by the environment variable `RMW_IMPLEMENTATION` (similar as `rosidl_typesupport_c|cpp`).
The next step after this has been merged will be to remove all rmw specific targets and only build targets against this "meta" rmw implementation (see ros2/ros2#302).
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2188)](http://ci.ros2.org/job/ci_linux/2188/)
* Mac OS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=1666)](http://ci.ros2.org/job/ci_osx/1666/)
* Windows [![Build …

make rmw_implementation a meta rmw implementation

---

rmw_implementation/src/functions.cpp

Refactor get topic names and types

---

rmw_implementation/src/functions.cpp

Fixes ros2/demos#177.
"Normal" set of builds:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3309)](http://ci.ros2.org/job/ci_linux/3309/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=574)](http://ci.ros2.org/job/ci_linux-aarch64/574/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2639)](http://ci.ros2.org/job/ci_osx/2639/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3347)](http://ci.ros2.org/job/ci_windows/3347/)
Special build on Linux which repeats the `pendulum_demo` test until fail for 100 times:
* [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3309)](http://ci.ros2.org/job/ci_linux/3309/)

fix deadlock

---

rmw_implementation/src/functions.cpp

This slightly updates #28 to:
* update the macro names (underscore between name and number)
* remove semicolons after macro calls
* declare `rmw_init` explicitly to avoid the `init_fn` argument as well as the `FOO_INIT` macro
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3338)](http://ci.ros2.org/job/ci_linux/3338/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=598)](http://ci.ros2.org/job/ci_linux-aarch64/598/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2668)](http://ci.ros2.org/job/ci_osx/2668/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3387)](http://ci.ros2.org/job/ci_windows/3387/)

simplify code relaying all symbols

---

rmw_implementation/package.xml

Connect to ament/ament_package#63

use format 3

---

rmw_implementation/src/functions.cpp

https://github.com/ros2/rmw/pull/124/ url on rmw.
The patch enables setting log severity from userland applications. The parameter
passed is defined inside rmw/include/types.h
Signed-off-by: Sriram Raghunathan <sriram.max@gmail.com>
Connect to ros2/rmw#124

API to enable log severity setting. 

---

rmw_implementation/package.xml

* Add build dependency on each current rmw implementations
* Add a comment indicating how runtime dependencies will be handled for debian packaging.

Prepare dependencies for bouncy release.

---

rmw_implementation/rmw_implementation-extras.cmake.in

In the case where `selected_rmw_implementation` is `rmw_implementation` it shouldn't call `find_package` for it since the entire logic already happens in the CMake config file of `rmw_implementation` so it is already "inside" a `find_package(rmw_implementation)` call.
This only doesn't end in an infinite recursion due to the custom logic in the generated CMake config files which returns early from repeated finds: https://github.com/ament/ament_cmake/blob/6d171d79584319c216e6880c46372224cd3ae6eb/ament_cmake_core/cmake/core/templates/nameConfig.cmake.in#L3-L7
Connect to ros2/ros2#544.

avoid recursive find

---

rmw_implementation/src/functions.cpp

use semicolons after macros

---

rmw_implementation/CMakeLists.txt
rmw_implementation/rmw_implementation-extras.cmake.in

This PR is based on the work that @anup-pem did internally at Apex. He found that cross compiling ROS2 caused the warning below, which doesn't show up when compiling natively because `pthread` is found on the host but not on the sysroot.
The fix just removes the `ament_export_libraries(pthread)` call and delegates the logic to the extras file.
/cc @filiperinaldi @lmayencourt 
```
--- stderr: velodyne_driver                                  
CMake Warning at /home/anup.pemmaiah/2394/apex_ws/install/share/rmw_implementation/cmake/ament_cmake_export_libraries-extras.cmake:116 (message):
Package 'rmw_implementation' exports library 'pthread' which couldn't be
found
:
:
---
```

Export threading library via extras and not ament_export_libraries to avoid warnings when cross-compiling

---

rmw_implementation/CMakeLists.txt

Resolves #58
\cc @dirk-thomas
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ros2/rmw_implementation/59)

cmake: Add `RMW_IMPLEMENTATION_FORCE_POCO`

---

rmw_implementation/src/functions.cpp

Rmw preallocate

---

rmw_implementation/src/functions.cpp

This change is to allow events that occur in the rmw layer related to missed deadlines and liveliness policies to be surfaced up to a user. It adds a new parameter to some existing functions and also adds several new functions in support of the liveliness QoS setting and taking events in general. 
Connects to ros2/rmw#171
Related to https://github.com/ros2/design/pull/212

QoS Events and Liveliness

---

rmw_implementation/src/functions.cpp

Currently, publishers have the get_actual_qos() feature/function. It would make sense for subscriptions to have them, too.

Implement get_actual_qos() for subscriptions

---

rmw_implementation/CMakeLists.txt
rmw_implementation/rmw_implementation-extras.cmake.in

Defer list of available RMWs to build time of downstream packages so you can build a dependent package even if RMW_IMPLEMENTATION is set to a value not available when the rmw_implementation package was built.
Remove CMake Config flag "RMW_IMPLEMENTATION_FORCE_DYNAMIC_LOADING".
Add CMake Config flag "RMW_IMPLEMENTATION_DISABLE_RUNTIME_SELECTION" so you can statically link a middleware, even if multiple present at build time. This value can be explicitly set, but by default preserves the behavior of "statically link if one middleware found".
Add a scary message if the user tries to change the implementation and built with RMW_IMPLEMENTATION_DISABLE_RUNTIME_SELECTION=ON

Make middleware selection more independent of build-time package availability

---

rmw_implementation/CMakeLists.txt

I don't think we need to tweak the link_directories to get this Poco to link properly

remove unneeded line from CMakeLists

---

rmw_implementation/CMakeLists.txt
rmw_implementation/package.xml
rmw_implementation/rmw_implementation/__init__.py

This pull request adds a basic Python API to lookup available RMW implementations in the system. Useful when parameterizing `pytests` by RMW implementation in pure Python packages i.e. no CMake templates available. 
Opening PR as a draft for preliminary discussion on whether this functionality should live here or in a separate package of its own.

Add Python API for RMW implementation lookups

---

rmw_implementation/src/functions.cpp

connected to https://github.com/ros2/ros2/issues/785

Zero copy api

---

rmw_implementation/src/functions.cpp

As the title says, adds the boolean localhost parameter to the create node api. Connected to this [issue](https://github.com/ros2/ros2/issues/798)
- Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8441)](https://ci.ros2.org/job/ci_linux/8441/)
- Arch [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4343)](https://ci.ros2.org/job/ci_linux-aarch64/4343/)
- Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=8352)](https://ci.ros2.org/job/ci_windows/8352/)
- OSX [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=6866)](https://ci.ros2.org/job/ci_osx/6866/)

Add localhost boolean parameter to create node function

---

rmw_implementation/src/functions.cpp

connects to https://github.com/ros2/rclcpp/pull/896
Signed-off-by: Karsten Knese <karsten@openrobotics.org>

rename return functions for loaned messages

---

rmw_implementation/src/functions.cpp

As a part of implementing [this](https://github.com/ros2/rmw/issues/151) feature. The RMW layer needs to expose apis to retrieve a list of publishers and subscribers along with their QoS policies for a given topic.
- rmw_get_qos_for_subscribers to get the qos policies for subscribers to
a topic
- rmw_get_qos_for_publishers to a get the qos policies for publishers to
a topic
Merge this PR after [this](https://github.com/ros2/rmw/pull/186) is approved as the new functions depend on the newly created structure `rmw_participants_t`

Added functions to get qos policies for publishers and subscribers to a topic

---

rmw_implementation/CMakeLists.txt
rmw_implementation/package.xml
rmw_implementation/src/functions.cpp

Compadre of https://github.com/ros2/rcpputils/pull/4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ros2/rmw_implementation/57)
Connects to ros2/rcpputils#4

Add `rcpputils` for `find_library`

---

rmw_implementation/src/functions.cpp

Style update to match the ROS 2 development guide and pass with the updated linter configuration from ament/ament_lint#210.

code style only: wrap after open parenthesis if not in one line

---

rmw_implementation/package.xml

Support discontinued from ROS Foxy onwards.
Find a discussion here: https://discourse.ros.org/t/opensplice-move-to-eclipse-cyclone-dds-in-ros-2/12370

Remove OpenSplice dependency

---

rmw_implementation/src/functions.cpp

Related to https://github.com/ros2/ros2/issues/822
This adds the `rmw_publisher_event_init()` and `rmw_subscription_event_init()` functions to `rmw_implementation` so that they will be able to check for whether or not the given type of `rmw_event_type_t` is supported by the chosen middleware.

Add rmw_*_event_init() functions to rmw_implementation

---

rmw_implementation/src/functions.cpp

Minimal renaming as part of https://github.com/ros2/rmw/issues/183.

Use one participant per context API changes

---

rmw_implementation/CMakeLists.txt
rmw_implementation/package.xml
rmw_implementation/src/functions.cpp

As part of the effort to remove Poco dependency described in this issue https://github.com/ros2/ros2/issues/867 this PR makes use of the recent changes in rcutils https://github.com/ros2/rcutils/pull/215 to load, unload and get symbols from shared libraries instead of using Poco.

Removed poco dependency

---

rmw_implementation/package.xml

Python code was removed in this https://github.com/ros2/rmw_implementation/pull/85/files but the dependency remains in the package.xml

Removed ament_cmake_python from package.xml

---

rmw_implementation/src/functions.cpp

Proposal to add timestamps on service request and response (for ros2/design#259)
This requires https://github.com/ros2/rmw/pull/217

Adapt interfaces for service timestamps

---

QUALITY_DECLARATION.md

Precisely what the title says. As discussed offline, we defer unit testing and rely on integration and system tests up the stack for this package (at least for the time being).

Update quality declaration on feature testing

---

test_rmw_implementation/CMakeLists.txt
test_rmw_implementation/package.xml
test_rmw_implementation/test/test_init_shutdown.cpp

Precisely what the title says. To serve as a basis for upcoming generic RMW API tests. Includes dummy init/shutdown test.

Add test_rmw_implementation package.

---

test_rmw_implementation/package.xml

https://github.com/ros2/rmw_implementation/pull/106#issuecomment-648489712
@hidmic FYI

Add dependency on ament_cmake_gtest

---

test_rmw_implementation/test/test_init_shutdown.cpp

Precisely what the title says. Follow-up after #106.

Complete init/shutdown API test coverage.

---

test_rmw_implementation/CMakeLists.txt
test_rmw_implementation/test/allocator_testing_utils.h
test_rmw_implementation/test/test_init_options.cpp

Needs https://github.com/ros2/rmw_fastrtps/pull/399, https://github.com/ros2/rmw_connext/pull/431 and https://github.com/ros2/rmw_cyclonedds/pull/200.

Add init options API test coverage.

---

test_rmw_implementation/test/test_init_shutdown.cpp

Connected to https://github.com/ros2/rmw/pull/247.

Check that rmw_init() fails if no enclave is given.

---

test_rmw_implementation/CMakeLists.txt
test_rmw_implementation/test/test_create_destroy_node.cpp

First stab at testing `rmw_create_node()` and `rmw_destroy_node()`.

Add node construction/destruction API test coverage.

---

test_rmw_implementation/CMakeLists.txt
test_rmw_implementation/test/config.hpp
test_rmw_implementation/test/test_publisher.cpp
test_rmw_implementation/test/test_subscription.cpp
test_rmw_implementation/test/testing_macros.hpp

Connected to https://github.com/ros2/rmw/pull/262. Depends on https://github.com/ros2/rmw_fastrtps/pull/424, https://github.com/ros2/rmw_connext/pull/451, and https://github.com/ros2/rmw_cyclonedds/pull/223.

Add publisher/subscription matched count API test coverage.

---

test_rmw_implementation/test/test_publisher.cpp

These two assertions duplicate the two immediately above them.

Remove duplicate assertions

---

test_rmw_implementation/test/test_serialize_deserialize.cpp

Precisely what the title says. 
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12378)](http://ci.ros2.org/job/ci_linux/12378/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7347)](http://ci.ros2.org/job/ci_linux-aarch64/7347/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10090)](http://ci.ros2.org/job/ci_osx/10090/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12290)](http://ci.ros2.org/job/ci_windows/12290/)

Add rmw_get_serialization_format() smoke test.

---

test_rmw_implementation/test/test_publisher.cpp
test_rmw_implementation/test/test_subscription.cpp

Affecting `rmw_create_publisher()` and `rmw_create_subscription()` tests.
CI up to `test_rmw_implementation`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12405)](http://ci.ros2.org/job/ci_linux/12405/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7372)](http://ci.ros2.org/job/ci_linux-aarch64/7372/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10115)](http://ci.ros2.org/job/ci_osx/10115/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12318)](http://ci.ros2.org/job/ci_windows/12318/)

Add missing empty topic name tests.

---

test_rmw_implementation/CMakeLists.txt
test_rmw_implementation/test/test_graph_api.cpp

This pull request adds tests for each graph query API when used with bad arguments.

Bump graph API test coverage.

---

test_rmw_implementation/CMakeLists.txt
test_rmw_implementation/test/test_unique_identifiers.cpp

Precisely what the title says. Connected tohttps://github.com/ros2/rmw/pull/274. Depends on https://github.com/ros2/rmw_fastrtps/pull/440, https://github.com/ros2/rmw_cyclonedds/pull/244, and https://github.com/ros2/rmw_connext/pull/461.

Add gid API test coverage.

---

test_rmw_implementation/CMakeLists.txt
test_rmw_implementation/test/test_publisher_allocator.cpp
test_rmw_implementation/test/test_subscription_allocator.cpp

Added `rmw_publisher_allocation` and `rmw_subscription_allocation` related tests. This functions are unimplemented. Arguments inside the functions are all casted to void to avoid warnings.

Added rmw_publisher_allocation and rmw_subscription_allocation related tests

---

rmw_implementation/src/functions.cpp
rmw_implementation/src/functions.hpp
rmw_implementation/test/benchmark/benchmark_symbols.cpp

This can be used to test the loading sequence for each RMW. I can already see that there is some investigation to do for Cyclone DDS.
~~I also renamed the `symbol_rmw_init` global variable to follow our naming convention and made it static.~~
~~https://index.ros.org/doc/ros2/Contributing/Code-Style-Language-Versions/#variable-naming~~

Expose a semi-private function for unloading the RMW lib

---

test_rmw_implementation/CMakeLists.txt
test_rmw_implementation/test/test_client.cpp
test_rmw_implementation/test/test_service.cpp

Precisely what the title says. Depends on https://github.com/ros2/rmw_fastrtps/pull/445, https://github.com/ros2/rmw_cyclonedds/pull/247, and https://github.com/ros2/rmw_connext/pull/464.

Add service/client construction/destruction API test coverage.

---

test_rmw_implementation/test/test_serialize_deserialize.cpp

Related with:
- https://github.com/ros2/rmw_fastrtps/pull/452
- https://github.com/ros2/rmw_connext/pull/467
- https://github.com/ros2/rmw_cyclonedds/pull/250 
- Updated API: https://github.com/ros2/rmw/pull/281

Added test for rmw_get_serialized_message_size

---

rmw_implementation/test/test_functions.cpp

Precisely what the title says. Follow up after #127.
CI up to `rmw_implementation`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12525)](http://ci.ros2.org/job/ci_linux/12525/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7494)](http://ci.ros2.org/job/ci_linux-aarch64/7494/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10237)](http://ci.ros2.org/job/ci_osx/10237/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12444)](http://ci.ros2.org/job/ci_windows/12444/)

Add nominal test for symbol prefetch() and unload.

---

test_rmw_implementation/CMakeLists.txt
test_rmw_implementation/test/test_wait_set.cpp

CI up to `test_rmw_implementation` and `rcl`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12539)](http://ci.ros2.org/job/ci_linux/12539/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7508)](http://ci.ros2.org/job/ci_linux-aarch64/7508/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10251)](http://ci.ros2.org/job/ci_osx/10251/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12460)](http://ci.ros2.org/job/ci_windows/12460/)

Fix test_wait_set.cpp to not wait on uninitialized arrays.

---

test_rmw_implementation/test/test_service.cpp

Follow-up after #141. 
CI up to `test_rmw_implementation`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12559)](http://ci.ros2.org/job/ci_linux/12559/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7527)](http://ci.ros2.org/job/ci_linux-aarch64/7527/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10270)](http://ci.ros2.org/job/ci_osx/10270/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12481)](http://ci.ros2.org/job/ci_windows/12481/)

Use 10x the intraprocess delay to wait for sent requests.

---

test_rmw_implementation/CMakeLists.txt
test_rmw_implementation/test/test_client.cpp

Testing:
- rmw_client
- rmw_destroy_client
- rmw_service_server_is_available
Related to this PR
- https://github.com/ros2/rmw_fastrtps/pull/447

Added rmw_client, rmw_destroy_client and rmw_service_server_is_available tests

---

test_rmw_implementation/test/test_client.cpp
test_rmw_implementation/test/test_publisher.cpp
test_rmw_implementation/test/test_serialize_deserialize.cpp
test_rmw_implementation/test/test_service.cpp
test_rmw_implementation/test/test_subscription.cpp

This tests should add 10 lines of coverage to `rmw_fastrtps_cpp`

Add tests bad type_support implementation

---

rmw_implementation/src/functions.cpp
rmw_implementation/src/functions.hpp

This will reduce coverage somewhat, as the conditions on which these exceptions are generated cannot be reproduced (yet).
CI up to `rmw_implementation`, `test_rmw_implementation`, and `rcl`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12685)](http://ci.ros2.org/job/ci_linux/12685/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7648)](http://ci.ros2.org/job/ci_linux-aarch64/7648/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10400)](http://ci.ros2.org/job/ci_osx/10400/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12628)](http://ci.ros2.org/job/ci_windows/12628/)

Fix up C functions to never throw.

---

test_rmw_implementation/test/test_service.cpp

This test checks that `rmw_send_response` sends `RMW_RET_OK` when the client has gone before sending the response.
I have checked that this test fails with the current `rmw_fastrtps_cpp` and `rmw_fastrtps_dynamics_cpp` implementations but it passes with changes from ros2/rmw_fastrtps#467.
Other rmw implementations tested under this package are currently passing the test.
Signed-off-by: JLBuenoLopez-eProsima <joseluisbueno@eprosima.com>

Add test to check rmw_send_response when the client is gone

---

test_rmw_implementation/test/test_service.cpp
test_rmw_implementation/test/test_wait_set.cpp

Pointed out by clang static analysis.  This is just a little
more correct.

Add some additional checking that cleanup happens.

---

rmw_implementation/src/functions.cpp

Connected to https://github.com/ros2/rcutils/pull/320. By deferring path resolution to the dynamic linker, RPATHs and RUNPATHs entries as well as LD_LIBRARY_PATH and PATH envvars are dealt with the standard way. Pre-linked and pre-loaded libraries are also honored. 
CI up to `test_communication`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13267)](http://ci.ros2.org/job/ci_linux/13267/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8198)](http://ci.ros2.org/job/ci_linux-aarch64/8198/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10987)](http://ci.ros2.org/job/ci_osx/10987/) (known test failure)
* Windows [![Build …

Defer path resolution of rmw implementation libraries to dynamic linker.

---

test_rmw_implementation/test/test_client.cpp

clang static analysis pointed out that if we never did *any*
iterations of the loop in SLEEP_AND_RETRY_UNTIL, then we
would be comparing an uninitialized value of rmw_ret_t with
RMW_RET_OK.  Just set it to RMW_RET_ERROR in this unlikely
case which will cause us to fail the test.

Set the return value of rmw_ret_t before entering the loop.

---

rmw_implementation/rmw_implementation-extras.cmake.in

The `get_default_rmw_implementation` macro contains the same functionality as is removed by this change, but it contains logic to fall back to any available RMW implementation if neither `RMW_IMPLEMENTATION` is specified nor the default is available.

Accept any RMW implementation, not just the default

---

test_rmw_implementation/test/test_client.cpp

clang static analysis pointed out that if we never did *any*
iterations of the loop in SLEEP_AND_RETRY_UNTIL, then we
would be comparing an uninitialized value of is_available with
false.  Just set it to false in this unlikely case.

Set the value of is_available before entering the loop.

---

test_rmw_implementation/test/test_subscription.cpp

The documentation for "rmw_take_sequence" says:
"Given `message_sequence` must be a valid message sequence, initialized
by rmw_message_sequence_init() and populated with ROS messages whose
type matches the message type support registered with the `subscription`
on creation."
As it stands, the take_sequence test fulfills the first part of that
(it was initialized by rmw_message_sequence_init()), but doesn't fulfill
the second part (populated by ROS messages).  In certain situations,
this could lead to an aborted test later on.  Make sure to do the
initialization to a known type before calling rmw_take_sequence.
This fixes the test part of the problem in https://github.com/ros2/rmw_cyclonedds/issues/279 .  There is still some …

Make sure to initialize the rmw_message_sequence after init.

---

rmw_implementation/package.xml

The `rmw_fastrtps_dynamic_cpp` package, which is in the same repository as `rmw_fastrtps_cpp`, declares itself as a member of the `rmw_implementation_packages` group. For completeness, and also because it is necessary for pre-resolved groups to be comprehensive for RPM packaging purposes, the explicit group list should contain this package.
The longer explanation of the motivation for this change stems from the lack of support for what RPM calls "[boolean dependencies](https://rpm.org/user_doc/boolean_dependencies.html)" in RHEL 7. We currently use this sort of mechanism in patching our debians to express a group relationship on "one or more group members". To achieve the same behavior in the RPM spec files, the group members declare that they provide a virtual package for the group, and …

Add rmw_fastrtps_dynamic_cpp to the explicit group deps

---

rmw_implementation/CMakeLists.txt

The line length enforcement in ament_lint_cmake has been broken for some time, but will be fixed by ament/ament_lint#236. This change brings this package into compliance with a 120 column limit.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13645)](http://ci.ros2.org/job/ci_linux/13645/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8525)](http://ci.ros2.org/job/ci_linux-aarch64/8525/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11360)](http://ci.ros2.org/job/ci_osx/11360/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=13709)](http://ci.ros2.org/job/ci_windows/13709/)

Shorten some excessively long lines of CMake

---

rmw_implementation/package.xml
test_rmw_implementation/test/config.hpp

This PR replaces all references to `rmw_connext_cpp` with `rmw_connextdds`.
See [rticommunity/rmw_connextdds #9](https://github.com/rticommunity/rmw_connextdds/issues/9) for a list of related PRs, and an overview of all the changes required to replace [ros2/rmw_connext](https://github.com/ros2/rmw_connext) (`rmw_connext_cpp`) with [rticommunity/rmw_connextdds](https://github.com/rticommunity/rmw_connextdds) in the ROS2 source tree.

Add support for rmw_connextdds

---

test_rmw_implementation/test/test_subscription.cpp

While testing ros2/rmw_fastrtps#523 I discovered [these non-implemented tests](https://github.com/ros2/rmw_implementation/blob/59a549597862659f7fcbaa9f025406a11946ec54/test_rmw_implementation/test/test_subscription.cpp#L810-L828)
This PR provides an implementation for them.

Implement test for subscription loaned messages

---

rmw_implementation/src/functions.cpp
rmw_implementation/test/test_functions.cpp

https://github.com/ros2/rcutils/pull/340 deprecates `rcutils/get_env.h`. This PR doesn't need to wait until the `rcutils` PR is merged, though.
I simply removed the `#include` since nothing from that header was actually used.

Remove unused headers

---

rmw_implementation/CMakeLists.txt
rmw_implementation/package.xml
rmw_implementation/src/functions.cpp

The old logic was to load what the user asked for (via the
RMW_IMPLEMENTATION environment variable).  If the user didn't
explicitly ask for an implementation, then it would attempt
to load the default RMW implementation.
The new logic is to load what the user asked for.  If the user
didn't explicitly ask for an implementation, attempt to load
the default RMW.  If that fails for some reason, fall back to
loading any available RMW.  If all of that fails, fail the
load.
One important thing to note about this PR is that it introduces a dependency between `rmw_implementation` and `ament_index_cpp`.  I don't *think* that is a problem, but it bears thinking about.
Besides making the code more robust, this PR should fix problems we …

Attempt to load any available RMW implementation.

---

test_rmw_implementation/test/test_client.cpp
test_rmw_implementation/test/test_service.cpp

Current tests assume service server and client in the same process discover each other immediately. That doesn't seem to be true for `rmw_connextdds` and thus [the flakes in amd64 Linux repeated CI](https://ci.ros2.org/view/nightly/job/nightly_linux_repeated/lastCompletedBuild/testReport/(root)/projectroot/test_service__rmw_connextdds/), which can be reproduced locally (FYI @asorbini). 
This patch amends this. 
Repeated CI up to `test_rmw_implementation`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14554)](http://ci.ros2.org/job/ci_linux/14554/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9311)](http://ci.ros2.org/job/ci_linux-aarch64/9311/)
* macOS [![Build …

Wait for server in test_rmw_implementation service tests

---

rmw_implementation/src/functions.cpp
test_rmw_implementation/test/test_publisher.cpp

Add rmw_publisher_wait_for_all_acked

---

test_rmw_implementation/test/test_subscription.cpp

Signed-off-by: Jose Antonio Moral <joseantoniomoralparras@gmail.com>
Related to https://github.com/ros2/rmw_fastrtps/pull/536

Test SubscriptionOptions::ignore_local_publications

---

test_rmw_implementation/CMakeLists.txt
test_rmw_implementation/test/test_duration_infinite.cpp

Followup to https://github.com/ros2/rmw/pull/301 - adding a compliance test so that RMW implementations are guaranteed to handle these values properly.
Tests pass locally against all default checked-out RMW implementations:
* `rmw_fastrtps`
* `rmw_cyclonedds`
* `rmw_connext`
* `rmw_connextdds`
For context, https://github.com/ros2/rosbag2/issues/756 was an uncaught case of this being a problem. It led to  ros2/rmw_connextdds#43, where @jacobperron recommended I create this test.
For a failing case, I reverted  ros2/rmw_connextdds#43 in a [branch](https://github.com/emersonknapp/rmw_connextdds/tree/revert-43), and rant this test against that version to see a failure.

Add RMW_DURATION_INFINITE basic compliance test

---

test_rmw_implementation/test/test_service.cpp

This backports #162 to Foxy once ros2/rmw_fastrtps#469 is merged.

[Backport Foxy] Add test to check rmw_send_response when the client is gone

---

rmw_implementation/Doxyfile
rmw_implementation/package.xml

Precisely what the title says. Needs https://github.com/ros-infrastructure/rosdoc2/pull/33.

Fix rmw_implementation generated documentation

---

rmw_implementation/src/functions.cpp

`rcpputils/get_env.hpp` is renamed to `rcpputils/env.hpp` as part of https://github.com/ros2/rcpputils/pull/150, so the corresponding includes have been fixed in this PR.
Signed-off-by: Abrar Rahman Protyasha <aprotyas@u.rochester.edu>

Fix renamed `rcpputils` header

---

rmw_implementation/src/functions.cpp
test_rmw_implementation/test/test_client.cpp
test_rmw_implementation/test/test_service.cpp

Blocked by https://github.com/ros2/rmw_fastrtps/pull/560
https://github.com/ros2/rmw_cyclonedds/pull/343
https://github.com/ros2/rmw_connextdds/pull/67
Signed-off-by: Mauro Passerino <mpasserino@irobot.com>

Add client/service QoS getters

---

test_rmw_implementation/test/test_client.cpp
test_rmw_implementation/test/test_service.cpp

Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>
Small PR, should fix linter issues introduced with #196
CI testing `test_rmw_implementation` before PR:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=15646)](http://ci.ros2.org/job/ci_linux/15646/)
CI after PR:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=15647)](http://ci.ros2.org/job/ci_linux/15647/)
(Checking full CI after linux CI passes)

Fix linter issues

---

rmw_implementation/CMakeLists.txt
rmw_implementation/rmw_implementation-extras.cmake.in

@Blast545 FYI this is an attempt to fix the CI issue from ros2/rmw_cyclonedds#357
~Requires ros2/rmw_cyclonedds#360~ :heavy_check_mark: 
~Requires ros2/realtime_support#112~ :heavy_check_mark: 
The package `rmw_implementation` appears to be the CMake interface between downstream libraries like `rcl` and the actual rmw implementations. It looks like when there are multiple rmw_implementations it will export a shared library that can load and switch between them, but when there is only one implementation it sets old-style standard CMake variables to the underlying implementation. Unfortunately, the latter expects the rmw implementation to set old-style CMake variables instead of modern CMake targets.
This PR creates an `IMPORTED` target `rmw_implementation::rmw_implementation` and variable …

Support and prefer exported targets from rmw implementations

---

rmw_implementation/src/functions.cpp

Relates to https://github.com/ament/ament_lint/pull/324

Fix relative path include syntax for cpplint

---

rmw_implementation/src/functions.cpp

This PR introduces the changes required to implement the `EventsExecutor` design in rmw.
See [design](https://github.com/ros2/design/pull/305) and [Discourse post](https://discourse.ros.org/t/ros2-middleware-change-proposal/15863).
The new executor uses an events queue and a timers manager as opposed to waitsets, to efficiently execute entities with work to do.
This new executor greatly reduces CPU usage of a ROS 2 application.
See the blog post for more details on the tests that we run.
The bulk of the changes for this implementation are in the rclcpp layer, with some minor changes in other repositories (rcl, rmw, rmw_implementation) for forwarding entities, the declaration of some data types in rcutils, and finally some additional changes in the vendor specific rmw implementations..
We …

Add EventsExecutor

---

rmw_implementation/src/functions.cpp
test_rmw_implementation/test/test_subscription.cpp

Related to https://github.com/ros2/design/pull/282 to add content-filtered-topic interfaces.

add content-filtered-topic interfaces

---

rmw_implementation/CMakeLists.txt

As per subject.
Should fix #209.

Don't find_package(ament_index_cpp ..) if RMW is configured at build-time

---

rmw_implementation/CMakeLists.txt
test_rmw_implementation/CMakeLists.txt

The two reasons to do this are:
1. So that we can compile rmw_implementation with the clang static analyzer. As of clang++-14 (what is in Ubuntu 22.04), the default still seems to be C++14, so we need to specify C++17 so that new things in the rclcpp headers work properly.
2. So we can build with a newer version of gtest which requires this.
Further, due to reasons I don't fully understand, I needed to set CMAKE_CXX_STANDARD_REQUIRED in order for clang to really use that version. So set this as well.

Update rmw_implementation to C++17.

---

rmw_implementation/src/functions.cpp

This PR is part of the runtime interface reflection subscription feature of REP-2011: https://github.com/ros2/ros2/issues/1374
This PR specifies linking/symbol finding for the new rmw methods defined in other PRs in #1374

Runtime Interface Reflection: rmw_implementation

---

rmw_implementation/src/functions.cpp
test_rmw_implementation/CMakeLists.txt
test_rmw_implementation/test/test_graph_api.cpp

this PR is for service counts using it's name like topic.
Related to https://github.com/ros2/ros2cli/pull/771
Signed-off-by: leeminju531 <dlalswn531@naver.com>

Add rmw_count_clients,services & test

---

rmw_implementation/CMakeLists.txt
test_rmw_implementation/CMakeLists.txt
test_rmw_implementation/package.xml

There is just no need to use ament_target_dependencies here.

Switch to using target_link_libraries everywhere.

---

test_rmw_implementation/CMakeLists.txt
test_rmw_implementation/test/test_client.cpp
test_rmw_implementation/test/test_create_destroy_node.cpp
test_rmw_implementation/test/test_duration_infinite.cpp
test_rmw_implementation/test/test_event.cpp
test_rmw_implementation/test/test_graph_api.cpp
test_rmw_implementation/test/test_init_options.cpp
test_rmw_implementation/test/test_init_shutdown.cpp
test_rmw_implementation/test/test_publisher.cpp
test_rmw_implementation/test/test_publisher_allocator.cpp
test_rmw_implementation/test/test_qos_profile_check_compatible.cpp
test_rmw_implementation/test/test_serialize_deserialize.cpp
test_rmw_implementation/test/test_service.cpp
test_rmw_implementation/test/test_subscription.cpp
test_rmw_implementation/test/test_subscription_allocator.cpp
test_rmw_implementation/test/test_unique_identifiers.cpp
test_rmw_implementation/test/test_wait_set.cpp

We really only need to compile them once, and then we can run them with different RMW implementations.
This also neatly sidesteps an incompatibility between current uncrustify and the newer one.

Compile the test_rmw_implementation tests fewer times.

---

test_rmw_implementation/test/test_subscription.cpp

This PR adds the proper test in `test_rmw_implementation` that checks for a successful creation of two content filter topics for the same topic name.
* Related PR https://github.com/ros2/rmw_fastrtps/pull/762

Add test creating two content filter topics with the same topic name

---

test_rmw_implementation/test/test_wait_set.cpp

https://github.com/ros2/rmw/pull/275 changed the `rmw_destroy_wait_set()` API documentation to indicate that it returns `RMW_RET_INVALID_ARGUMENT` if `wait_set` is `NULL`. However, this wasn't the case in practice in the implementations of `rmw_destroy_wait_set()` or in the relevant test.
Change the test here to expect `RMW_RET_INVALID_ARGUMENT`.
Required `rmw` implementation PRs:
* https://github.com/ros2/rmw_cyclonedds/pull/498
* https://github.com/ros2/rmw_fastrtps/pull/766
* https://github.com/ros2/rmw_connextdds/pull/152
* (`rmw_zenoh` already returns `RMW_RET_INVALID_ARGUMENT` in this case)

Expect rmw_destroy_wait_set to ret RMW_RET_INVALID_ARGUMENT

---

test_rmw_implementation/test/test_client.cpp

https://github.com/ros2/rmw/pull/277 changed the `rmw_service_server_is_available()` API documentation to indicate that it returns `RMW_RET_INVALID_ARGUMENT` if `node`, `client`, or `is_available` are `NULL`. However, this wasn't the case in practice in the implementations of `rmw_service_server_is_available()` or in the relevant test.
Change the test here to expect `RMW_RET_INVALID_ARGUMENT`.
Required `rmw` implementation PRs:
* https://github.com/ros2/rmw_cyclonedds/pull/496
* https://github.com/ros2/rmw_fastrtps/pull/763
* https://github.com/ros2/rmw_connextdds/pull/150
* (`rmw_zenoh` already returns `RMW_RET_INVALID_ARGUMENT` in this case)

Expect rmw_service_server_is_available to ret RMW_RET_INVALID_ARGUMENT

---

test_rmw_implementation/test/test_publisher.cpp

[`rmw_return_loaned_message_from_publisher()`](https://github.com/ros2/rmw/blob/ac4f9afccca3dc305f2b519fdb0fb9131250f2a5/rmw/include/rmw/rmw.h#L483) and [`rmw_publish_loaned_message()`](https://github.com/ros2/rmw/blob/ac4f9afccca3dc305f2b519fdb0fb9131250f2a5/rmw/include/rmw/rmw.h#L621) accept a `void *`, not a `void **`.
It built fine, but probably failed at runtime. I guess none of the `rmw`s currently exercise this part of the test.

Do not deref msg ptr for rmw_{publish,return}_loaned_message*()
